name: Continuous Integration

on:
  pull_request:
  merge_group:
    types:
      - checks_requested

concurrency:
  group: ci-checks-${{ github.event.pull_request && github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  check-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
      
        
      
