name: Continuous Integration

on:
  pull_request:
  merge_group:
    types:
      - checks_requested

concurrency:
  group: ci-checks-${{ github.event.pull_request && github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  check-pr:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test
