name: Publish Package to npmjs

on:
  release:
    types: [published]
  push:
    branches: [publish-package-gh-action]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Enable Corepack
        run: corepack enable

      - run: yarn
      - run: HUSKY=0 yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}
